# Generated by Django 5.0.1 on 2025-04-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='aceita_localizacao',
        ),
    ]
