# Generated by Django 5.0.1 on 2025-04-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_perfilusuario_aceita_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
