# Generated by Django 5.0.1 on 2025-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_latitude_perfilusuario_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='latitude',
            field=models.FloatField(default=-12.9714),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='longitude',
            field=models.FloatField(default=-38.5014),
        ),
    ]
