# Generated by Django 5.0.1 on 2025-04-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_bio_perfilusuario_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='aceita_localizacao',
            field=models.BooleanField(default=False),
        ),
    ]
